version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
    - zookeeper
  postgres:
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - app-data:/var/lib/postgresql/data
    environment:
    - POSTGRES_DB=mydb
    - POSTGRES_USER=postgres 
    - POSTGRES_PASSWORD=password
#  app:
#    build: 
#      context: .
#      dockerfile: Dockerfile
#    ports:
#    - 8080:8080
#    depends_on:
#    - postgres

volumes:
  app-data:
  
 
    